eight_points_guzzle:
    clients:
        gwentup:
            base_url: "https://gwentup.com"            
            options:
                verify: false
                timeout: 30
                headers:
                    User-Agent: "Nightbot/1.0"
            plugin: ~
        bitly:
            base_url: "https://api-ssl.bitly.com"            
            options:
                verify: false
                timeout: 30
                headers:
                    User-Agent: "Nightbot/1.0"
            plugin: ~            
