framework:
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: ~

    #esi: true
    #fragments: true
    php_errors:
        log: true

    cache:
parameters:
    gwentup_id: "%env(GWENT_ID)%"
    bitly_login: "%env(BITLY_LOGIN)%"
    bitly_token: "%env(BITLY_TOKEN)%"
